### ISSUE TITLE
how to pause UIManger's update while dynamic create UIElements

### ISSUE THREAD

**Issue by xlla** [MyreMylar/pygame_gui#165]
To change arrow button's width, I have extend UIHorizontalSlider. 
change default_button_width and call rebuild() in overrides function show().

<pre>
2236-MainThread 2020-11-06 19:14:12,873 piCameraApp.py:143 mainloop     ERROR - 'NoneType' object has no attribute 'held'
Traceback (most recent call last):
  File "piCameraApp.py", line 141, in mainloop
    self.manager.update(time_delta)
  File "/usr/lib/python3.7/site-packages/pygame_gui/ui_manager.py", line 252, in update
    self.ui_group.update(time_delta)
  File "/usr/lib/python3.7/site-packages/pygame_gui/core/layered_gui_group.py", line 276, in update
    super().update(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pygame-2.0.0.dev12-py3.7-linux-aarch64.egg/pygame/sprite.py", line 531, in update
    sprite.update(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pygame_gui/elements/ui_horizontal_slider.py", line 265, in update
    if self.sliding_button.held and self.sliding_button.in_hold_range((mouse_x, mouse_y)):
AttributeError: 'NoneType' object has no attribute 'held'
</pre>

**Comment by xlla** [comment]
another exception:
<pre>
Traceback (most recent call last):
  File "piCameraApp.py", line 141, in mainloop
    self.manager.update(time_delta)
  File "/usr/lib/python3.7/site-packages/pygame_gui/ui_manager.py", line 248, in update
    element_handled_hover = ui_element.check_hover(time_delta, hover_handled)
  File "/usr/lib/python3.7/site-packages/pygame_gui/core/ui_element.py", line 508, in check_hover
    self.hover_point(mouse_x, mouse_y) and
  File "/usr/lib/python3.7/site-packages/pygame_gui/elements/ui_button.py", line 197, in hover_point
    return (self.drawable_shape.collide_point((hover_x, hover_y)) and
AttributeError: 'NoneType' object has no attribute 'collide_point'
</pre>

**Comment by xlla** [comment]
I have many UIPanel created dynamic while a gpio button pressed, it seems the manager.update() in outer loop will try to process those UIElements under construction, so those exceptions raised.

**Comment by xlla** [comment]
I am try to modify the lib with many additional 'None' check logic, unfortunately, the new exception raise.
<pre>
3000-MainThread 2020-11-08 23:46:23,131 piCameraApp.py:143 mainloop     ERROR - 'UIButton' object has no attribute 'is_selected'
Traceback (most recent call last):
  File "piCameraApp.py", line 141, in mainloop
    self.manager.update(time_delta)
  File "/usr/lib/python3.7/site-packages/pygame_gui/ui_manager.py", line 248, in update
    element_handled_hover = ui_element.check_hover(time_delta, hover_handled)
  File "/usr/lib/python3.7/site-packages/pygame_gui/core/ui_element.py", line 503, in check_hover
    if self.alive() and self.can_hover():
  File "/usr/lib/python3.7/site-packages/pygame_gui/elements/ui_button.py", line 208, in can_hover
    return not self.is_selected and self.is_enabled and not self.held
AttributeError: 'UIButton' object has no attribute 'is_selected'
</pre>

So I think it should have a mechanism to let UIManager pause/skip update.

**Comment by MyreMylar** [comment]
Are you using multiple threads here?

**Comment by xlla** [comment]
Yes, I think so. I want to create some UI panel on demand, when a gpio button was pressed.

**Comment by MyreMylar** [comment]
Well it sounds like you'd be better off putting a message into a queue from your GPIO thread and then creating the new button on the pygame/pygame_gui thread. 

You don't normally want to pause your drawing code for a dynamic GUI like this (it does things like animated fades and typing style text effects which happen independent of user interaction). The reason the GUI is built to be dynamic is because games are normally dynamic too so they work well together. There are lots of other GUIs that use an event driven drawing model (user clicked so redraw button).

**Comment by xlla** [comment]
Ok , I got it.
