### ISSUE TITLE
Trying to use Nuitka to package a game using pygame_gui.

### ISSUE THREAD

**Issue by Zageron** [MyreMylar/pygame_gui#214]
**Describe the bug**
I've seen a few examples of issues around including the pygame_gui/data directory but I can't figure out how to get it to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build anything with pygame_gui
2. Try to launch it.

**Expected behaviour**
Game should launch.

**Screenshots**

**Platform and software (please complete the following information):**
 - OS: Windows
 - 0.5.7
 - 2.0.2

**Additional context**
```bash
PS L:\git\zageron\snake\package> .\Snake.exe
pygame 2.0.2 (SDL 2.0.16, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\pygame_gui\core\ui_font_dictionary.py:116: UserWarning: Unable to load resource with path: <pygame_gui.core.utility.PackageResource object at 0x00000000356A2B80>
Traceback (most recent call last):
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\importlib\resources.py", line 97, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Zageron\\AppData\\Local\\Temp\\ONEFIL~1\\pygame_gui\\data\\default_theme.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\__main__.py", line 336, in <module>
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\__main__.py", line 206, in main
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\pygame_gui\ui_manager.py", line 54, in __init__
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\pygame_gui\core\ui_appearance_theme.py", line 101, in __init__
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\pygame_gui\core\ui_appearance_theme.py", line 113, in _load_default_theme_file
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\pygame_gui\core\ui_appearance_theme.py", line 645, in load_theme
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\importlib\resources.py", line 139, in read_text
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\importlib\resources.py", line 121, in open_text
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\importlib\resources.py", line 111, in open_binary
FileNotFoundError: 'default_theme.json' resource not found in 'pygame_gui.data'
```

Commands I'm trying:
```bash
nuitka --onefile --plugin-enable=numpy --plugin-enable=pylint-warnings --include-plugin-directory=pygame_gui/data -o package/Snake.exe --output-dir=package --remove-output src/snake/__main__.py
```

`Nuitka-Recursion:WARNING: Failed to recurse to directory 'pygame_gui\\data'.`

Really not sure how to approach this issue.

**Comment by MyreMylar** [comment]
@Zageron 

I've managed to build a test pygame_gui program with nuitka. The key is this part:

```
--include-package-data=pygame_gui.data
```
For your program I guess it would be something like:

```
nuitka --onefile --plugin-enable=numpy --plugin-enable=pylint-warnings --include-package-data=pygame_gui.data -o package/Snake.exe --output-dir=package --remove-output src/snake/__main__.py
```

Though when I release 0.6.0 there will likely be some sub packages in data to keep it organised, I'm not sure if nuitka recursively searches subdirectories.

Let me know if that works and I'll close this out with a section in the docs.

**Comment by Zageron** [comment]
Thanks I'll give it a shot sometime soon. I haven't had opportunities to work on this lately.

**Comment by MyreMylar** [comment]
Added a new page on freezing scripts to the documentation for 0.6.0.

**Comment by Zageron** [comment]
@MyreMylar Apologies for the massive delay I finally got to checking this.
```
L:\git\zageron\snake-py\package>Snake.exe
Traceback (most recent call last):
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\__main__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\pygame\__init__.py", line 298, in <module pygame>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\pygame\surfarray.py", line 47, in <module pygame.surfarray>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\numpy\__init__.py", line 144, in <module numpy>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\numpy\core\__init__.py", line 23, in <module numpy.core>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\numpy\core\multiarray.py", line 80, in <module numpy.core.multiarray>
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\numpy\core\overrides.py", line 201, in decorator
  File "C:\Users\Zageron\AppData\Local\Temp\ONEFIL~1\numpy\core\overrides.py", line 183, in decorator
RuntimeError: __code__ is not writable in Nuitka
```

**Comment by Zageron** [comment]
I upgraded to 0.6.0 before and after testing this, same result. If you have no thoughts, I'll check in Nuitka as well.

**Comment by MyreMylar** [comment]
Those look like numpy errors, not pygame ones. I don't use numpy in
pygame_gui.

**Comment by Zageron** [comment]
You are correct.

Here's the next error I am running into.

```
Traceback (most recent call last):
  File "L:\git\zageron\snake-py\package\__main__.dist\__main__.py", line 336, in <module>
  File "L:\git\zageron\snake-py\package\__main__.dist\__main__.py", line 206, in main
  File "L:\git\zageron\snake-py\package\__main__.dist\pygame_gui\ui_manager.py", line 66, in __init__
  File "L:\git\zageron\snake-py\package\__main__.dist\pygame_gui\core\ui_appearance_theme.py", line 59, in __init__
  File "L:\git\zageron\snake-py\package\__main__.dist\pygame_gui\core\ui_font_dictionary.py", line 127, in __init__
  File "L:\git\zageron\snake-py\package\__main__.dist\pygame_gui\core\ui_font_dictionary.py", line 155, in _load_default_font
  File "L:\git\zageron\snake-py\package\__main__.dist\pygame_gui\core\utility.py", line 384, in load
  File "L:\git\zageron\snake-py\package\__main__.dist\importlib\abc.py", line 371, in read_bytes
  File "L:\git\zageron\snake-py\package\__main__.dist\importlib\_adapters.py", line 54, in open
ValueError
```

**Comment by Zageron** [comment]
![image](https://user-images.githubusercontent.com/1892473/149607628-2ce33da0-8d0a-4d6e-8cf8-91d08552362b.png)

**Comment by MyreMylar** [comment]
I just successfully turned your snake repo into a nuitka .exe using this command:

`nuitka --onefile --include-package-data=pygame_gui.data --include-data-dir=data=data -o package/Snake.exe --output-dir=package --remove-output src/snake/__main__.py`

But to make your program work at all I had to fix paths for the non-standard entry point/working directory setup you must have for the project in VSCode. By which I mean your `main` is nested two subdirectories deep, but your working directory is set at the highest package level. 

Most things (like nuitka I guess) are going to assume where main is, is the working directory.

Anyway, this just meant changing two things:

Line 17 of main.py becomes:

`from score import Score`

and line 206 becomes:

`manager = pygame_gui.UIManager((WINSIZE[0], WINSIZE[1]), "../../data/theme.json")`

Then the code would run normally for me with the working directory as the same directory as your main entry point - and it ran as an exe after I packaged it with nuitka.

**Comment by Zageron** [comment]
Oh that's such a silly mistake! D:
Thank you so much, I apologize for having to rely on your good graces and time to get this to work. Really appreciate it.

**Comment by Zageron** [comment]
I am having zero luck getting this to work with your example.

I was having an issue where no matter what I tried, when passing the path in to theme_path it was ending up being: `L:\data\theme.json` so I had to use os.getcwd() instead. No other example I have found online has given me the correct path, and this is clearly happening here as well.

I wonder if this is happening because I am using poetry / virtualenv as my build environment, but that seems unlikely.

```
L:\git\zageron\snake-py\package\__main__.dist
L:\git\zageron\snake-py\package\__main__.dist\data\theme.json
```

```python
    # PyGame GUI
    root_path = os.path.join(os.sep, os.getcwd())
    theme_path = os.path.join(root_path, "data", "theme.json")

    print(root_path)
    print(theme_path)

    manager = pygame_gui.UIManager(
        (WINSIZE[0], WINSIZE[1]),
        theme_path=theme_path,
    )
```

I think I'm ready to give up and just continue working on future projects.
