### ISSUE TITLE
Importin Windows spesific ctypes causes traceback

### ISSUE THREAD

**Issue by jtiai** [MyreMylar/pygame_gui#29]
When trying yo use examples on Linux following traceback appears:
```python
Traceback (most recent call last):
  File "/home/jtiai/projects/pygame_gui/pygame_gui_examples/general_ui_test_app.py", line 4, in <module>
    from pygame_gui.ui_manager import UIManager
  File "/home/jtiai/projects/pygame_gui/pygame_gui/__init__.py", line 3, in <module>
    from . import elements
  File "/home/jtiai/projects/pygame_gui/pygame_gui/elements/__init__.py", line 11, in <module>
    from .ui_text_entry_line import UITextEntryLine
  File "/home/jtiai/projects/pygame_gui/pygame_gui/elements/ui_text_entry_line.py", line 8, in <module>
    from ..core.utility import clipboard_paste, clipboard_copy
  File "/home/jtiai/projects/pygame_gui/pygame_gui/core/utility.py", line 7, in <module>
    from ctypes.wintypes import HGLOBAL, LPVOID, BOOL, UINT, HANDLE, HWND, DWORD, INT, HMENU, HINSTANCE, LPCSTR
  File "/usr/lib/python3.7/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported
```

Root cause of traceback is attempt to import Windows specific ctypes `ctypes.wintypes` which is only available on Windows.

**Comment by MyreMylar** [comment]
Thanks.

Getting some linux testing up and running today on a raspberry pi hopefully
so I should be able to squash this and any other things that slipped
through the cracks.
