### ISSUE TITLE
pygame.error: font not initialized

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#60]
**Describe the bug**
Reinstalled all of my libraries and now pygame_gui fails to load. Errors on self.loaded fonts below, in ui_font_dictionary.py with "pygame.error: font not initialized".

    def load_default_font(self, default_font_file_path: str, module_root_path: str):
        # Only use the 'stringified' data if we can't find the actual default font file
        # This is need for a working PyInstaller build
        if os.path.exists(default_font_file_path):
            self.loaded_fonts = {self.default_font_id: pygame.font.Font(default_font_file_path,
                                                                        self.default_font_size)}

**To Reproduce**
Steps to reproduce the behaviour:
1.  Run the main .py.
2. Crashes on init.

**Platform and software (please complete the following information):**
 - OS: [Windows 10 64-bit]
 - Pygame GUI version [0.4.2]
 - Pygame version [2.0.0dev6]

**Additional context**
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Gabriel\Documents\NotQuiteParadise\scripts\managers\input_manager.py", line 12, in <module>
    from scripts.managers.ui_manager import ui
  File "C:\Users\Gabriel\Documents\NotQuiteParadise\scripts\managers\ui_manager.py", line 58, in <module>
    ui = UIManager()
  File "C:\Users\Gabriel\Documents\NotQuiteParadise\scripts\managers\ui_manager.py", line 18, in __init__
    "data/ui/themes.json")
  File "C:\Users\Gabriel\Documents\NotQuiteParadise\venv\lib\site-packages\pygame_gui\ui_manager.py", line 19, in __init__
    self.ui_theme = UIAppearanceTheme()
  File "C:\Users\Gabriel\Documents\NotQuiteParadise\venv\lib\site-packages\pygame_gui\core\ui_appearance_theme.py", line 75, in __init__
    self.font_dictionary = UIFontDictionary()
  File "C:\Users\Gabriel\Documents\NotQuiteParadise\venv\lib\site-packages\pygame_gui\core\ui_font_dictionary.py", line 60, in __init__
    self.load_default_font(default_font_file_path, module_root_path)
  File "C:\Users\Gabriel\Documents\NotQuiteParadise\venv\lib\site-packages\pygame_gui\core\ui_font_dictionary.py", line 69, in load_default_font

    self.default_font_size)}
pygame.error: font not initialized

**Comment by Snayff** [comment]
Issue unrelated to pygame_gui. I needed to move the pygame_init to earlier in the process.
